[env:esp32p4_pioarduino]
platform = https://github.com/pioarduino/platform-espressif32.git#54.03.21
upload_speed = 1500000
monitor_speed = 115200
build_type = debug
framework = arduino
extra_scripts = pre:scripts/filter_lvgl_asm.py
board = esp32-p4-evboard
board_build.mcu = esp32p4
board_build.variant = m5tab5
board_build.variants_dir = variants
board_build.flash_mode = qio
board_build.partitions = default_16MB.csv
build_flags =
    -DBOARD_HAS_PSRAM
    -DCORE_DEBUG_LEVEL=5
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DVEGA_ENABLE_MQTT=1
    -D LV_CONF_INCLUDE_SIMPLE
    -I include
lib_deps =
    https://github.com/M5Stack/M5Unified.git#8b63555e7bd9ac71978c55ad868fd1d1d3b2ef3e
    https://github.com/M5Stack/M5GFX.git#b863d50dd3ca57b65c61a468001925fee70b3e05
    lvgl/lvgl @ 9.2.2
