#!/usr/bin/env python3
"""Generate compact AtomS3 route data from the repository's course catalog."""

import argparse
import json
from pathlib import Path

PROJECT = Path(__file__).resolve().parents[1]
REPO = PROJECT.parents[1]
CATALOG = REPO / "assets" / "course_manifest.json"
OUTPUT = PROJECT / "include" / "generated_courses.h"


def number(value, digits=7):
    return f"{float(value):.{digits}f}"


def generate():
    manifest = json.loads(CATALOG.read_text())
    lines = [
        "// Generated by scripts/generate_courses.py; do not edit by hand.",
        "#pragma once",
        "#include <stdint.h>",
        "namespace sim {",
        "struct Point { float east_m, north_m, s_m; };",
        "struct Route { const Point *points; uint16_t count; float length_m; };",
        "struct Course { const char *id; const char *name; const char *short_name; uint8_t lap_count;",
        "  double origin_lat, origin_lon, east_per_lon, north_per_lat;",
        "  Route first, regular, final; };",
    ]
    entries = []
    for index, item in enumerate(manifest["courses"]):
        path = CATALOG.parent / item["folder"] / item["source"]
        data = json.loads(path.read_text())
        sequence = data["race_sequence"]
        laps = len(sequence)
        expected = ["first_lap"] + ["regular_lap"] * (laps - 2) + ["final_lap"]
        if laps < 2 or [lap["route_id"] for lap in sequence] != expected:
            raise ValueError(f"unsupported race sequence: {path}")
        routes = []
        for key in ("first_lap", "regular_lap", "final_lap"):
            route = data["routes"][key]
            points = route["points"]
            if len(points) < 2 or len(points) > 65535:
                raise ValueError(f"invalid points: {path}, {key}")
            if abs(points[0]["s_m"]) > 0.01 or abs(points[-1]["s_m"] - route["length_m"]) > 0.1:
                raise ValueError(f"inconsistent length: {path}, {key}")
            name = f"course_{index}_{key}"
            lines.append(f"static const Point {name}[] = {{")
            for point in points:
                lines.append("  {" + ", ".join(number(point[k], 6) + "f" for k in ("east_m", "north_m", "s_m")) + "},")
            lines.append("};")
            routes.append(f"{{{name}, {len(points)}, {number(route['length_m'], 6)}f}}")
        cs = data["coordinate_system"]
        entries.append("  {" + ", ".join([
            json.dumps(item["folder"]), json.dumps(item["name"]),
            json.dumps(item["short_name"]), str(laps),
            number(cs["origin_lat_deg"], 9), number(cs["origin_lon_deg"], 9),
            number(cs["east_m_per_lon_deg"], 9), number(cs["north_m_per_lat_deg"], 9),
            *routes,
        ]) + "},")
    lines.extend(["static const Course courses[] = {", *entries, "};",
                  "static constexpr uint8_t course_count = sizeof(courses) / sizeof(courses[0]);",
                  "} // namespace sim", ""])
    return "\n".join(lines)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated header is stale")
    args = parser.parse_args()
    output = generate()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != output:
            parser.error(f"{OUTPUT} is stale; run this script without --check")
    else:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(output)
        print(f"wrote {OUTPUT}")
