#!/usr/bin/env python3
"""Embed course geometry and transform from the canonical asset (no image generation)."""
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
source = ROOT / "assets/motegi_oval/motegi_course.json"
data = json.loads(source.read_text())
cs = data["coordinate_system"]
matrix = [v for row in data["render"]["local_to_pixel_matrix_2x3"] for v in row]
lines = [
    "// Generated by scripts/generate_course_data.py; edit the JSON asset.",
    "// Source SHA256: " + hashlib.sha256(source.read_bytes()).hexdigest(),
    "#pragma once",
    '#include "domain/course.h"',
    "namespace tab5 {",
    "inline constexpr vega::CoursePoint course_points[] = {",
]
for p in data["points"]:
    lines.append("  {%s, %s, %s}," % (p["east_m"], p["north_m"], p["s_m"]))
lines += [
    "};",
    "inline const vega::CourseData course_data{",
    "  course_points, sizeof(course_points)/sizeof(course_points[0]), %s,"
    % data["length_m"],
    "  {%s, %s}, %s, %s,"
    % (
        cs["origin_lat_deg"],
        cs["origin_lon_deg"],
        cs["east_m_per_lon_deg"],
        cs["north_m_per_lat_deg"],
    ),
    "  {{" + ", ".join(map(str, matrix)) + "}}",
    "};",
    "}",
]
(ROOT / "src/adapters/course_data.h").write_text("\n".join(lines) + "\n")
