#!/usr/bin/env python3
"""Embed one schema-2 course and its pixel transform in a C++ header."""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--source", type=Path, default=Path("assets/motegi_oval_full/motegi_course_full.json"))
parser.add_argument("--output", type=Path, default=Path("src/adapters/course_data.h"))
args = parser.parse_args()
source = args.source if args.source.is_absolute() else ROOT / args.source
output = args.output if args.output.is_absolute() else ROOT / args.output
data = json.loads(source.read_text())
if data["schema_version"] != 2:
    raise ValueError("Expected the full course schema (version 2)")
expected_sequence = ["first_lap"] + ["regular_lap"] * 5 + ["final_lap"]
if [entry["route_id"] for entry in data["race_sequence"]] != expected_sequence:
    raise ValueError("The seven-lap race sequence does not match the firmware route model")
if (data["render"]["width_px"], data["render"]["height_px"]) != (480, 480):
    raise ValueError("The EEZ course image must be 480 x 480 pixels")
for asset_name in (data["render"]["background"], data["render"]["svg"]):
    if not (source.parent / asset_name).is_file():
        raise ValueError(f"Missing course artwork: {asset_name}")
cs = data["coordinate_system"]
matrix = [v for row in data["render"]["local_to_pixel_matrix_2x3"] for v in row]
paths = {
    "first": data["routes"]["first_lap"],
    "regular": data["routes"]["regular_lap"],
    "final": data["routes"]["final_lap"],
}
if "finish_approach" in data["segments"]:
    paths["finish_approach"] = data["segments"]["finish_approach"]
lines = [
    "// Generated by scripts/generate_course_data.py; edit the JSON asset.",
    "// Source SHA256: " + hashlib.sha256(source.read_bytes()).hexdigest(),
    "#pragma once",
    '#include "domain/course.h"',
    "namespace tab5 {",
]
for name, path in paths.items():
    points = path["points"]
    if (
        len(points) < 2
        or points[0]["s_m"] != 0
        or path["length_m"] <= 0
        or abs(points[-1]["s_m"] - path["length_m"]) > 0.01
        or any(b["s_m"] <= a["s_m"] for a, b in zip(points, points[1:]))
    ):
        raise ValueError(f"Invalid {name} path")
    lines.append(f"inline constexpr vega::CoursePoint {name}_points[] = {{")
    for p in points:
        lines.append("  {%s, %s, %s}," % (p["east_m"], p["north_m"], p["s_m"]))
    lines.append("};")
regular = paths["regular"]
lines += [
    "inline const vega::CourseData course_data{",
    "  regular_points, sizeof(regular_points)/sizeof(regular_points[0]), %s,"
    % regular["length_m"],
    "  {%s, %s}, %s, %s,"
    % (
        cs["origin_lat_deg"],
        cs["origin_lon_deg"],
        cs["east_m_per_lon_deg"],
        cs["north_m_per_lat_deg"],
    ),
    "  {{" + ", ".join(map(str, matrix)) + "}},",
    "  {{",
]
for name in ("first", "regular", "final", "finish_approach"):
    if name in paths:
        path = paths[name]
        lines.append(
            "    {%s_points, sizeof(%s_points)/sizeof(%s_points[0]), %s, %s},"
            % (name, name, name, path["length_m"], str(path["closed"]).lower())
        )
    else:
        lines.append("    {},")
lines += [
    "  }},",
    "  " + json.dumps(data["course_id"]),
    "};",
    "}",
]
output.parent.mkdir(parents=True, exist_ok=True)
output.write_text("\n".join(lines) + "\n")
